:sectnums:
== Terms and definitions

////
解釈がずれると困る用語を書く。Glossaryという参考用語集を設けることは可能。
必ず3章に書かなければいけない？
標準化として定義された単語でなければならない（論文から引用するのはダメ）。このサイトから検索できる https://www.iso.org/obp/ui/
基本的なAI用語はこのISO/IECが基準になりそう: https://www.iso.org/obp/ui/#iso:std:iso-iec:22989:ed-1:v1:en:term:3.1.27
Note that the initial notice about terms ("This document uses the terms defined in OGC Policy Directive 49...")
is inserted automatically by Metanorma using the agreed standardised language, and you should not enter it here.
////

=== Geospatial Foundation Models
models trained on large-scale EO datasets and aim to capture fundamental geospatial features that can be leveraged for downstream tasks 

[.source]
<<PANGAEA>>

=== benchmark
procedure, problem, or test that can be used to compare systems or components to each other or to a standard

[.source]
<<ISOIECIEEE_24765, ISO/IEC/IEEE 24765:2017>>

=== multimodal model (bands, sensor)
machine learning models capable of processing and integrating information from multiple modalities or types of data. These modalities can include text, images, audio, video and other forms of sensory input. 
[.source]
<<ISOIECIEEE_24765, ISO/IEC/IEEE 24765:2017>>

In EO domain, they also can include sensors.

=== single temporal, multi-temporal

=== robustness
ability of a system to maintain its level of performance under any circumstances
[.source]
<<ISOIEC_22989, ISO/IEC 22989:2022>>


// [.source]
// <<ISO19101-1>>

// NOTE: An example note.

// [example]
// Here's an example of an example term.

[appendix,obligation="informative"]
[heading='terms and definitions']
== Glossary
Landsat, Sentinel
...
